# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: colors-of-magic

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  region: eu-central-1

package:
  individually: true
  exclude:
    - "**"

# The `functions` block defines what code to deploy
functions:
  colorsOfMagic:
    handler: api/handler.colors
    events:
      - http:
          path: colorsOfMagic
          method: post
          cors: true
    package:
      include:
        - api/**
